export const GROUP_REALTIME_EVENT_TYPE = {
    CONNECTED: "REALTIME_CONNECTED",

    GROUP_MEMBER_JOINED: "GROUP_MEMBER_JOINED",
    GROUP_MEMBER_LEFT: "GROUP_MEMBER_LEFT",
    GROUP_DELETED: "GROUP_DELETED",

    GROUP_RECOMMENDATION_STARTED: "GROUP_RECOMMENDATION_STARTED",
    GROUP_RECOMMENDATION_READINESS_UPDATED: "GROUP_RECOMMENDATION_READINESS_UPDATED",
    GROUP_RECOMMENDATION_OPENED: "GROUP_RECOMMENDATION_OPENED",
    GROUP_RECOMMENDATION_VOTE_UPDATED: "GROUP_RECOMMENDATION_VOTE_UPDATED",
    GROUP_RECOMMENDATION_FINALIZED: "GROUP_RECOMMENDATION_FINALIZED",
} as const;

export type GroupRealtimeEventType =
    (typeof GROUP_REALTIME_EVENT_TYPE)[keyof typeof GROUP_REALTIME_EVENT_TYPE];