export const MY_REALTIME_EVENT_TYPE = {
    CONNECTED: "REALTIME_CONNECTED",
    GROUP_INVITE_CREATED: "GROUP_INVITE_CREATED",
    GROUP_RECOMMENDATION_VOTE_COMPLETED: "GROUP_RECOMMENDATION_VOTE_COMPLETED",
} as const;

export type MyRealtimeEventType =
    typeof MY_REALTIME_EVENT_TYPE[keyof typeof MY_REALTIME_EVENT_TYPE];